# Generated by Django 4.1.7 on 2023-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='fp',
            field=models.CharField(max_length=100),
        ),
    ]
